#!/bin/sh

set -ev

case "$TEST" in
    none)
        echo Tests skipped! >> "$1"
        ;;
    slow)
        echo Tested with cache disabled on `hostname`.  Took `cat /tmp/time.txt`. >> "$1"
        ;;
    *)
        echo Tested on `hostname`.  Took `cat /tmp/time.txt`. >> "$1"
        ;;
esac
