#!/bin/sh

set -ev

# Make sure we can run git add from out of tree:
export GIT_DIR=`pwd`/.git
export GIT_INDEX_FILE=`pwd`/$GIT_INDEX_FILE
export AM_RUNNING_PRECOMMIT=yes

# Create a clean temp directory for running tests:
TEMPDIR=`mktemp -d -t testing-XXXXXXXXX`
git checkout-index --prefix=$TEMPDIR/ -af
cd $TEMPDIR


case "$TEST" in
    none)
        echo Skipping all tests.
        ;;
    compile)
        echo Testing compile and papers.
        
        time bash .build
        echo Compile successful!
        
        ;;
    build)
        echo Testing build only.
        
        time bash .build
        echo Compile successful!
        
        time bash .papers
        echo Papers successfully built!
        ;;
    *)
        echo Testing everything!
        
        time bash .build
        echo Compile successful!
        
        time bash .papers
        echo Papers successfully built!

        time bash .test
        echo All tests passed!
        ;;
esac

cd /tmp
rm -rf $TEMPDIR
