#!/bin/sh

set -ev

# Make sure we can run git add from out of tree:
export GIT_DIR=`pwd`/.git
export GIT_INDEX_FILE=`pwd`/$GIT_INDEX_FILE
export AM_RUNNING_PRECOMMIT=yes

# Create a clean temp directory for running tests:
TEMPDIR=`mktemp -d -t testing-XXXXXXXXX`
git checkout-index --prefix=$TEMPDIR/ -af
cd $TEMPDIR

ALLCPUS=`grep -c processor /proc/cpuinfo || echo 1`
USING=${SLURM_CPUS_PER_TASK:-$ALLCPUS}

case "$TEST" in
    none)
        echo Skipping all tests.
        ;;
    slow)
        echo Testing very carefully!
        /usr/bin/time -f '%E' -o time.txt scons -j $USING --cache-disable
        echo Tests successful, took `cat time.txt`
        ;;
    *)
        echo Testing everything!
        /usr/bin/time -f '%E' -o time.txt scons -j $USING
        echo Tests successful, took `cat time.txt`
        ;;
esac

cd /tmp
rm -rf $TEMPDIR
