#!/usr/bin/python2.7

import os

repos = ['/home/droundy/git/deft.git',
         '/home/jordan/deft',
         '/home/kirstie/git/deft.git',
         '/home/kirstie/deft',
         '/home/lincoln/deft',
         '/home/tysonf/git/deft.git',
         '/home/cadetrotter/git/deft',
         '/home/cadetrotter/deft']

for repo in repos:
    os.system('git pull {} :'.format(repo))

