#!/usr/bin/python3

import os

repos = ['/home/droundy/git/deft.git',
         '/home/jordan/deft',
         '/home/kirstie/git/deft.git',
         '/home/kirstie/deft',
]

for repo in repos:
    os.system('git pull {} :'.format(repo))

