#!/usr/bin/python2

#This program produces temperature vs density, and pressure vs temperature phase diagrams
#from data stored in *best.dat (or *best_tensor.dat) data files generated by figs/new-melting.cpp

#NOTE: Run this plot script from directory deft/papers/fuzzy-fmt 
#with comand ./plot-phasediagram.py [Optional: --tensor]  >> phase_diagram_data.dat (or phase_diagram_data-tensor.dat)

from __future__ import print_function, division

import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import os, glob
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--tensor', action='store_true',
                    help='use tensor weight')
args=parser.parse_args()

p_at_freezing = []  #pressure at freezing (intersection point between homogeneous and crystal plots)
n_homogeneous_at_freezing =[]
n_crystal_at_freezing = []
hn_mid_at_p_list = []
cn_mid_at_p_list = []
kT_at_hp_list = []
kT_at_cp_list = []
pressures_to_plot = []   #may delete this
pressures_in_plot = []
kT_in_plot = []

kT_to_plot = [0.1, 0.2, 0.5, 1.0]
n_to_plot = [.61]
p_to_plot = [2, 20]

kT_data = []
density_data = []
pressure_data = []

for kT in np.arange(0.05, 1.15, 0.05):   #data files with these temperatures will be plotted
   
   n = []
   invn = []
   hfe = []
   cfe = []

   if args.tensor :
     files = sorted(list(glob.glob('crystallization/kT%.3f_n*_best_tensor.dat' % kT)))
     
   else :
      files = sorted(list(glob.glob('crystallization/kT%.3f_n*_best.dat' % kT)))

   for f in files:
      data = np.loadtxt(f)
      n.append(data[1])     #density
      invn.append(1/data[1])
      hfe.append(data[4])   #homogeneous free energy/atom
      cfe.append(data[5])   #crystal free energy/atom
   hfe = np.array(hfe)
   cfe = np.array(cfe)
   invn = np.array(invn)
   n = np.array(n)

   functions = np.vstack((np.ones_like(invn),
                       invn**-1,
                       invn**-2,
                       invn**-3,
                       invn**-4,
                       invn**-5,
                       invn**-6)).T
   pressure_functions = np.vstack((np.zeros_like(invn),
                                invn**-2,
                                2*invn**-3,
                                3*invn**-4,
                                4*invn**-5,
                                5*invn**-6,
                                6*invn**-7)).T
   A = np.linalg.lstsq(functions, cfe)
   coeff = A[0]
   #print('residuals', A[1])
   #print('coeff', coeff)
   fit_cfe = np.dot(functions, coeff)


   dhfe=np.diff(hfe)  #Caution: depends on order of data files!
   dcfe=np.diff(cfe)  #Caution: depends on order of data files!
   dinvn=np.diff(invn)  #Caution: depends on order of data files!
   mid_invn=invn[0:len(invn)-1]+dinvn/2
   hpressure = -(dhfe/dinvn) #for fixed N and Te   
   cpressure = -(dcfe/dinvn) #for fixed N and Te  

   fit_p = np.dot(pressure_functions, coeff)

   mid_hfe = 0.5*(hfe[1:] + hfe[:-1])
   mid_cfe = 0.5*(cfe[1:] + cfe[:-1])

   mid_h_gibbs = mid_hfe + mid_invn*hpressure
   mid_c_gibbs = mid_cfe + mid_invn*cpressure
   fit_c_gibbs = fit_cfe + invn*fit_p


   #Find pressure at point of intersection
   def find_first_intersection(p1, g1, p2, g2): 
      for i in range(1,len(g1)-1):
         m1=(g1[i+1]-g1[i])/(p1[i+1]-p1[i])
         for j in range(1,len(g2)-1):
               m2=(g2[j+1]-g2[j])/(p2[j+1]-p2[j])
               if m1!=m2 :
                  P_inter=(g2[j] - m2*p2[j] -g1[i] + m1*p1[i])/(m1-m2)
                  if p1[i] < P_inter < p1[i+1] and p2[j] < P_inter < p2[j+1]:
                     g_inter=m1*P_inter+g1[i]-m1*p1[i]
                     if g1[i] < g_inter < g1[i+1] and g2[j] < g_inter < g2[j+1] :
                           return P_inter, g_inter

   p_inter, g_inter = find_first_intersection(hpressure, mid_h_gibbs, cpressure, mid_c_gibbs)
   pf_inter, gf_inter = find_first_intersection(hpressure, mid_h_gibbs, fit_p, fit_c_gibbs)


   #Find homogeneous and crystal densities at p_inter
   def find_densities(p_inter, pressure, invn):
      for i in range(1,len(pressure)-1): 
         if pressure[i] > p_inter :
               pressureabove=pressure[i]
               invnabove=invn[i]
               pressurebelow=pressure[i-1]
               invnbelow=invn[i-1]
               m=(pressureabove-pressurebelow)/(invnabove-invnbelow)
               invn_inter=invnabove-((pressureabove-p_inter)/m)
               return invn_inter
   invnh=find_densities(p_inter, hpressure, mid_invn)
   invnc=find_densities(p_inter, cpressure, mid_invn)
   
   p_at_freezing.append(p_inter)   
   n_homogeneous_at_freezing.append(1/invnh)
   n_crystal_at_freezing.append(1/invnc)

   # compute the actual physical pressure as a function of density, and skip over coexistence
   actual_pressure = []
   actual_density = []
   for i in range(len(mid_invn)):
      if hpressure[i] >= p_inter:
         break
      actual_pressure.append(hpressure[i])
      actual_density.append(1/mid_invn[i])
   actual_pressure.append(p_inter)
   actual_density.append(1/invnh)
   actual_pressure.append(p_inter)
   actual_density.append(1/invnc)
   for i in range(len(mid_invn)):
      if cpressure[i] < 0:
         break
      if cpressure[i] > p_inter:
         actual_pressure.append(cpressure[i])
         actual_density.append(1/mid_invn[i])
   actual_pressure = np.array(actual_pressure)
   actual_density = np.array(actual_density)

   #print (kT, p_inter, 1/invnh, 1/invnc)   #Use >> phase_diagram_data.dat (or phase_diagram_data-tensor.dat) to store data for reference
   
   kT_data.append(kT)  #holds all values of kT in a list
   density_data.append(actual_density)
   pressure_data.append(actual_pressure)

n_homogeneous_at_freezing = np.array(n_homogeneous_at_freezing)
n_crystal_at_freezing = np.array(n_crystal_at_freezing)
p_at_freezing = np.array(p_at_freezing)

#For plotting T vs n, or n vs T at constant P --------
# for pressure in p_to_plot :
#    for i in range(0, len(kT_data)) :  #number of temperatures kT
#       for j in range(0, len(density_data[i])-1) :  #number of elements of n at some kT
#          if hpressure_data[i][j] < pressure < hpressure_data[i][j+1] :
#             hpressure_below=hpressure_data[i][j]
#             hpressure_above=hpressure_data[i][j+1] 
#             hn_below=density_data[i][j]
#             hn_above=density_data[i][j+1]
#             hn_mid=(hn_above-hn_below)/2 + hn_below
#             hn_mid_at_p_list.append(hn_mid)
#             #print("new", hpressure_below, pressure, hpressure_above)
#             #print("new", hn_below, hn_mid, hn_above)

#             kT_at_hp_list.append(kT_data[i])
            
#          if cpressure_data[i][j] < pressure < cpressure_data[i][j+1] :
#             cpressure_below=cpressure_data[i][j]
#             cpressure_above=cpressure_data[i][j+1] 
#             cn_below=density_data[i][j]
#             cn_above=density_data[i][j+1]
#             cn_mid=(cn_above-cn_below)/2 + cn_below
#             cn_mid_at_p_list.append(cn_mid)
#             #print("new", cpressure_below, pressure, cpressure_above)
#             #print("new", cn_below, cn_mid, cn_above)
            
#             kT_at_cp_list.append(kT_data[i])

#    #Plot T vs n  at constant P
#    plt.plot(hn_mid_at_p_list, kT_at_hp_list, label= 'P=%g' % (pressure))
#    plt.plot(cn_mid_at_p_list, kT_at_cp_list, label= 'P=%g' % (pressure))
#    plt.title("Temperature vs Number Density at fixed Pressure")
#    plt.legend(loc='best')
#    plt.xlabel('Number Density')
#    plt.ylabel('Temperature')  
   
#    # - OR - uncomment the plot you want
   
#    ##Plot n vs T  at constant P
#    #plt.plot(kT_at_hp_list, hn_mid_at_p_list, label= 'P=%g' % (pressure))
#    #plt.plot(kT_at_cp_list, cn_mid_at_p_list, label= 'P=%g' % (pressure))
#    #plt.title("Number Density vs Temperature at fixed Pressure")
#    #plt.legend(loc='best')
#    #plt.ylabel('Number Density')
#    #plt.xlabel('Temperature') 
# #-----------------------------------------------------    

plt.figure()

plt.fill_betweenx(p_at_freezing, n_homogeneous_at_freezing, n_crystal_at_freezing, color='#eeeeee') 
for i in range(len(kT_data)):
   if kT_data[i] in kT_to_plot or True:
      #Plot P vs n  at constant kT
      #plt.figure('pressure corresponding to data vs density')
      plt.plot(density_data[i], pressure_data[i], label= 'kT=%g' % kT_data[i])
plt.title("NEW Pressure vs Number Density at kT")
plt.legend(loc='best')
plt.ylim(0, 26)
plt.xlim(0, 1.1)
plt.xlabel('Number Density')
plt.ylabel('Pressure')

plt.figure()

plt.fill_betweenx(p_at_freezing, 1/n_homogeneous_at_freezing, 1/n_crystal_at_freezing, color='#eeeeee') 
for i in range(len(kT_data)):
   if kT_data[i] in kT_to_plot or True:
      #Plot P vs n  at constant kT
      #plt.figure('pressure corresponding to data vs density')
      plt.plot(1/density_data[i], pressure_data[i], label= 'kT=%g' % kT_data[i])
plt.title("NEW Pressure vs Number Density at kT")
plt.legend(loc='best')
plt.ylim(0, 26)
plt.xlim(0.95, 1.6)
plt.xlabel('Volume per atom')
plt.ylabel('Pressure')

# plt.figure()

# #Plot n vs P  at constant kT
# plt.plot(hpressure_data[1], density_data[1], label= 'hpressure kT=0.1')  
# plt.plot(cpressure_data[1], density_data[1], label= 'cpressure kT=0.1')  
# plt.plot(hpressure_data[3], density_data[3], label= 'hpressure kT=0.2')  
# plt.plot(cpressure_data[3], density_data[3], label= 'cpressure kT=0.2')
# plt.plot(hpressure_data[9], density_data[9], label= 'hpressure kT=0.5') 
# plt.plot(cpressure_data[9], density_data[9], label= 'cpressure kT=0.5') 
# plt.plot(hpressure_data[19], density_data[19], label= 'hpressure kT=1.0')  
# plt.plot(cpressure_data[19], density_data[19], label= 'cpressure kT=1.0')   
# plt.title("Number Density vs Pressure at kT")
# plt.legend(loc='best')
# plt.ylabel('Number Density')
# plt.xlabel('Pressure')

# plt.figure()

# #--------------FIX
# # Plot P vs T at constant n
# for i in range(0, len(kT_data)) : 
#    for j in range(0, len(density_data[i])) :
#       if density_data[i][j] in n_to_plot:
#          print(density_data[i][j]) 
#          pressures_in_plot.append(hpressure_data[i][j])
#          kT_in_plot.append(kT_data[i])
# plt.plot(pressures_in_plot, kT_in_plot, label= 'hpressure n=%g' % (density_data[i][j]), color='red')
# plt.plot(pressures_in_plot, kT_in_plot, label= 'hpressure n=', color='red')  
# plt.title("Pressure vs Temperature at n")
# plt.legend(loc='best')
# plt.ylabel('Pressure')
# plt.xlabel('Temperature')
# #------------FIX

plt.figure()

#Temperature vs Density Phase Diagram
plt.plot(n_homogeneous_at_freezing, kT_data, label='liquid', color='red')
plt.plot(n_crystal_at_freezing, kT_data, label='solid', color='blue')
plt.fill_betweenx(kT_data, .1, n_homogeneous_at_freezing, color='red')       
plt.fill_betweenx(kT_data, n_homogeneous_at_freezing, n_crystal_at_freezing, color='gray') 
plt.fill_betweenx(kT_data, n_crystal_at_freezing, 1.6, color='blue')        
plt.title("Temperature vs Number Density")
#plt.legend(loc='best')
plt.xlabel('Number Density')
plt.ylabel('Temperature')

plt.figure()

##Pressure vs Temperature Phase Diagram
plt.fill_between(kT_data, 0, p_at_freezing, color='red')      
plt.fill_between(kT_data, p_at_freezing, 26, color='blue')    #FIX - change 30
plt.plot(kT_data, p_at_freezing, color='black')
#plt.ylim(0, 40)
#plt.xlim(kT_data.min(), kT_data.max())     #FIX!  
plt.title("Pressure vs Temperature")
plt.xlabel('Temperature')
plt.ylabel('Pressure')

plt.show()
